"""领域枚举与统一中文文案。

所有跨模块交换的事件都只能使用这里登记的类型，避免不同服务各自造词。
"""

# ---- 聚合类型 ----
AGG_LIVE_SESSION = "live_session"
AGG_SEGMENT = "program_segment"
AGG_PARTICIPANT = "participant"
AGG_MATERIAL = "material_source"
AGG_PERMISSION = "usage_permission"
AGG_CONTRACT = "contract"
AGG_CONTRIBUTION = "viewer_contribution"
AGG_TIP = "tip_order"
AGG_REVENUE = "revenue_entry"
AGG_REPLAY = "replay_version"
AGG_CUT = "derived_cut"

AGGREGATE_TYPES = (
    AGG_LIVE_SESSION,
    AGG_SEGMENT,
    AGG_PARTICIPANT,
    AGG_MATERIAL,
    AGG_PERMISSION,
    AGG_CONTRACT,
    AGG_CONTRIBUTION,
    AGG_TIP,
    AGG_REVENUE,
    AGG_REPLAY,
    AGG_CUT,
)

# ---- 事件类型 ----
EV_SESSION_SCHEDULED = "SESSION_SCHEDULED"
EV_SESSION_STARTED = "SESSION_STARTED"
EV_SESSION_ENDED = "SESSION_ENDED"
EV_SEGMENT_REGISTERED = "SEGMENT_REGISTERED"
EV_PARTICIPANT_REGISTERED = "PARTICIPANT_REGISTERED"
EV_MATERIAL_LINKED = "MATERIAL_LINKED"
EV_MATERIAL_VERIFIED = "MATERIAL_VERIFIED"
EV_PERMISSION_GRANTED = "PERMISSION_GRANTED"
EV_CONSENT_CAPTURED = "CONSENT_CAPTURED"
EV_CONSENT_CONFIRMED = "CONSENT_CONFIRMED"
EV_CONSENT_WITHDRAWN = "CONSENT_WITHDRAWN"
EV_RELEASE_RESTRICTED = "RELEASE_RESTRICTED"
EV_RELEASE_CLEARED = "RELEASE_CLEARED"
EV_CONTRACT_EXECUTED = "CONTRACT_EXECUTED"
EV_CONTRIBUTION_RECEIVED = "CONTRIBUTION_RECEIVED"
EV_TIP_PLACED = "TIP_PLACED"
EV_TIP_REFUNDED = "TIP_REFUNDED"
EV_REVENUE_ALLOCATED = "REVENUE_ALLOCATED"
EV_RIGHTS_ADJUSTED = "RIGHTS_ADJUSTED"
EV_REPLAY_PUBLISHED = "REPLAY_PUBLISHED"
EV_REPLAY_TAKEN_DOWN = "REPLAY_TAKEN_DOWN"
EV_CUT_PROPOSED = "CUT_PROPOSED"
EV_CUT_PUBLISHED = "CUT_PUBLISHED"
EV_CUT_REJECTED = "CUT_REJECTED"

EVENT_TYPES = (
    EV_SESSION_SCHEDULED,
    EV_SESSION_STARTED,
    EV_SESSION_ENDED,
    EV_SEGMENT_REGISTERED,
    EV_PARTICIPANT_REGISTERED,
    EV_MATERIAL_LINKED,
    EV_MATERIAL_VERIFIED,
    EV_PERMISSION_GRANTED,
    EV_CONSENT_CAPTURED,
    EV_CONSENT_CONFIRMED,
    EV_CONSENT_WITHDRAWN,
    EV_RELEASE_RESTRICTED,
    EV_RELEASE_CLEARED,
    EV_CONTRACT_EXECUTED,
    EV_CONTRIBUTION_RECEIVED,
    EV_TIP_PLACED,
    EV_TIP_REFUNDED,
    EV_REVENUE_ALLOCATED,
    EV_RIGHTS_ADJUSTED,
    EV_REPLAY_PUBLISHED,
    EV_REPLAY_TAKEN_DOWN,
    EV_CUT_PROPOSED,
    EV_CUT_PUBLISHED,
    EV_CUT_REJECTED,
)

# ---- 用途 ----
USE_LIVE = "LIVE_BROADCAST"
USE_REPLAY = "REPLAY"
USE_COMMERCIAL_CUT = "COMMERCIAL_CUT"

USES = (USE_LIVE, USE_REPLAY, USE_COMMERCIAL_CUT)

USE_LABELS = {
    USE_LIVE: "直播",
    USE_REPLAY: "回放",
    USE_COMMERCIAL_CUT: "商业剪辑",
}

# ---- 许可/同意状态 ----
CONSENT_PENDING = "PENDING"          # 直播中临时口头同意，待补签
CONSENT_CONFIRMED = "CONFIRMED"      # 已完成正式授权
CONSENT_WITHDRAWN = "WITHDRAWN"      # 权利人撤回
CONSENT_STATES = (CONSENT_PENDING, CONSENT_CONFIRMED, CONSENT_WITHDRAWN)

# ---- 素材识别可信度（BGM 自动识别等）----
CERTAINTY_VERIFIED = "VERIFIED"
CERTAINTY_UNCERTAIN = "UNCERTAIN"
CERTAINTY_LEVELS = (CERTAINTY_VERIFIED, CERTAINTY_UNCERTAIN)

# ---- 受限原因 ----
REASON_PENDING_CONSENT = "PENDING_CONSENT"   # 口头同意尚未补签
REASON_MINOR_ON_MIC = "MINOR_ON_MIC"         # 未成年人连麦保护
REASON_BGM_UNVERIFIED = "BGM_UNVERIFIED"     # 背景音乐识别不确定
REASON_RIGHTS_EXPIRED = "RIGHTS_EXPIRED"     # 授权到期
REASON_NOT_LICENSED = "NOT_LICENSED"         # 完全没有授权
REASON_GEO_OUT_OF_SCOPE = "GEO_OUT_OF_SCOPE"  # 地域不在授权范围
REASON_WITHDRAWN = "PERMISSION_WITHDRAWN"    # 授权被撤回
REASON_MANUAL_HOLD = "MANUAL_HOLD"           # 人工复核挂起

REASONS = (
    REASON_PENDING_CONSENT,
    REASON_MINOR_ON_MIC,
    REASON_BGM_UNVERIFIED,
    REASON_RIGHTS_EXPIRED,
    REASON_NOT_LICENSED,
    REASON_GEO_OUT_OF_SCOPE,
    REASON_WITHDRAWN,
    REASON_MANUAL_HOLD,
)

# 编辑端可见完整原因
REASON_LABELS = {
    REASON_PENDING_CONSENT: "口头同意待补签确认",
    REASON_MINOR_ON_MIC: "未成年人连麦，保护性限制",
    REASON_BGM_UNVERIFIED: "背景音乐识别结果不确定，待核实",
    REASON_RIGHTS_EXPIRED: "授权已到期",
    REASON_NOT_LICENSED: "该素材尚未取得授权",
    REASON_GEO_OUT_OF_SCOPE: "当前地域不在授权范围内",
    REASON_WITHDRAWN: "授权已被权利人撤回",
    REASON_MANUAL_HOLD: "人工复核中，暂不发布",
}

# 观众端文案：涉及未成年人的原因不暴露细节，只做中性提示
VIEWER_REASON_LABELS = dict(REASON_LABELS)
VIEWER_REASON_LABELS[REASON_MINOR_ON_MIC] = "该时段因参与者权益保护暂不可用"
VIEWER_REASON_LABELS[REASON_PENDING_CONSENT] = "该时段授权正在核对中，暂不可用"

# ---- 素材类型 ----
MATERIAL_HERITAGE_DEMO = "HERITAGE_DEMO"      # 传承人示范
MATERIAL_ACCOMPANIMENT = "ACCOMPANIMENT"      # 伴奏曲目
MATERIAL_VOICE_LINK = "VOICE_LINK"            # 观众连麦
MATERIAL_PLATFORM_CLIP = "PLATFORM_CLIP"      # 平台切片
MATERIAL_OTHER = "OTHER"
MATERIAL_TYPES = (
    MATERIAL_HERITAGE_DEMO,
    MATERIAL_ACCOMPANIMENT,
    MATERIAL_VOICE_LINK,
    MATERIAL_PLATFORM_CLIP,
    MATERIAL_OTHER,
)

# ---- 参与者角色 ----
ROLE_INHERITOR = "INHERITOR"        # 非遗传承人
ROLE_MUSICIAN = "MUSICIAN"          # 伴奏/乐手
ROLE_VIEWER = "VIEWER"              # 连麦观众
ROLE_PLATFORM = "PLATFORM"          # 平台
ROLES = (ROLE_INHERITOR, ROLE_MUSICIAN, ROLE_VIEWER, ROLE_PLATFORM)

# ---- 结算调整类型 ----
ADJ_TOP_UP = "TOP_UP"              # 补付
ADJ_REVERSAL = "REVERSAL"          # 冲正
ADJUSTMENT_KINDS = (ADJ_TOP_UP, ADJ_REVERSAL)

ENTRY_INITIAL = "INITIAL_ALLOCATION"
ENTRY_REVERSAL = "REVERSAL"
REVENUE_ENTRY_KINDS = (ENTRY_INITIAL, ENTRY_REVERSAL)

# 阻断原因的展示优先级：越靠前越优先对外说明（未成年人保护优先于商业核对）
REASON_PRIORITY = (
    REASON_MINOR_ON_MIC,
    REASON_MANUAL_HOLD,
    REASON_WITHDRAWN,
    REASON_BGM_UNVERIFIED,
    REASON_RIGHTS_EXPIRED,
    REASON_PENDING_CONSENT,
    REASON_GEO_OUT_OF_SCOPE,
    REASON_NOT_LICENSED,
)

# ---- 发布闸门结论 ----
GATE_ALLOWED = "ALLOWED"
GATE_PARTIAL = "PARTIALLY_RESTRICTED"
GATE_BLOCKED = "BLOCKED"
